### PR TITLE
Introduce a new low level creation for clog element: 'create-element'

### PR DESCRIPTION
**Pull request by jingtaozf**
It is useful to integrate with bootstrap, for example:

```javascript
(create-element toolbar-row :div :class "btn-toolbar" :role "toolbar" :aria-label "Toolbar")
```
Or:
```javascript
(create-element toolbar-group-1 :button :content "F" :class "btn btn-primary" :title "a tooltip for a button")
```

### CODE REVIEW

**Comment by rabbibotton** [comment]
I plan on merging this at some point, but since you included https://github.com/rabbibotton/clog/pull/290 I first need to work out the potential issues first. I am now coding again after long break so hopefully won't be too long.

**Comment by rabbibotton** [comment]
I need to see how to prevent the portion that was #290 and then merge this.

**Review by rabbibotton — CHANGES_REQUESTED** [review]
This is the change that needs to be removed.

**Comment by jingtaozf** [comment]
@rabbibotton Is it possible for me to initiate a new pull request that solely includes `create-element`? I can likewise incorporate other modifications in subsequent pull requests as well.

**Comment by rabbibotton** [comment]
perfect

**Comment by jingtaozf** [comment]
I created a new pull request for `create-element`: https://github.com/rabbibotton/clog/pull/320

**Pull request closed without merging**
