### PR TITLE
Add "expand-region" and "macroexpand" functions to clog-builder text editor

### PR DESCRIPTION
**Pull request by rse3vau**
Hello!

I really love clog-builder and its editor, but it disappointed me that it's lacking some convenient functions I often use in Emacs. So I tried to add expand-region and macroexpand functions to it. 

Limited by my level, the code is a bit of ugly. Please tell me if there's any way to get improvement!

The expand-region function is inspired by the expand-region package in Emacs, but all of the codes are completed by my own (and that's why it's so ugly...). So there's no license problem~

Thanks for your awesome creation!

P.S. Could you please tell me whether you decide to add more Emacs's functions to clog-builder? Maybe I can take some help. And I'm not sure the hotkey I set for the new functions is suit for clog-builder's design, please change it if there's better choice.

### CODE REVIEW

**Comment by rabbibotton** [comment]
I'll try and review this morning. Awesome!! For sure want to add more features like emacs and for sure would love the help!!

**Comment by rabbibotton** [comment]
Sorry for the delay, going to merge now. I keep delaying expanding on menus, right click menus etc soon

**Comment by rabbibotton** [comment]
I removed for macroexpand button, keyboard opt-m still on of course, until can setup a better menu system. Look forward to using it and any other great add ons you come up with :)

**Comment by rse3vau** [comment]
Thank you, that's exciting! I could not wait to contribute more features!

**Pull request merged**
