### PR TITLE
Added GUI window pin/unpin

### PR DESCRIPTION
**Pull request by pankajgodbole**
Prevent or allow a window to be moved, closed, resized, maximized or normalized.

### CODE REVIEW

**Comment by rabbibotton** [comment]
I am going to merge today and will make it an option if the pinning appears on the title bar defaulting to no. That works for you?

**Comment by pankajgodbole** [comment]
Yes, That works for me.

Where will the user see this option?

Thanks.

**Comment by pankajgodbole** [comment]
Thanks! I'll check it out.

**Comment by rabbibotton** [comment]
Ok, just added. When creating the window add :has-pinner t take a look at tutorial 22

**Comment by rabbibotton** [comment]
I added a utf-8 ☑ to check and unchecked when pinned.

**Comment by rabbibotton** [comment]
Great addition to clog!

**Pull request merged**
